/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "streaming_rpc_constants.h"

namespace com { namespace lesgo { namespace thrift { namespace rpc { namespace streaming {

const streaming_rpcConstants g_streaming_rpc_constants;

streaming_rpcConstants::streaming_rpcConstants() {
}

}}}}} // namespace

