/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef streaming_rpc_CONSTANTS_H
#define streaming_rpc_CONSTANTS_H

#include "streaming_rpc_types.h"

namespace com { namespace lesgo { namespace thrift { namespace rpc { namespace streaming {

class streaming_rpcConstants {
 public:
  streaming_rpcConstants();

};

extern const streaming_rpcConstants g_streaming_rpc_constants;

}}}}} // namespace

#endif
